### ISSUE TITLE
make sure that address generated through vanity-solana is actually on curve

### ISSUE THREAD

**Issue by hromi** [m2-labs/solana-vanity-address#2]
Hello world,

I used vanity-solana to generate an wallet fo an important community project, it yielded the ADAMSUaPWvynZm2vxpQhuapRwxDuexNyjRqBoMtsiKUx

Unfortunately it seems that that public key is not on curve ( https://solscan.io/account/ADAMSUaPWvynZm2vxpQhuapRwxDuexNyjRqBoMtsiKUx ). 

I found it out only after I send some tokens to it. Luckily, not too much, but it is still unfortunate.

Please make sure that addresses Your tool generates are actually usable, otherwise it can lead to many unexpected surprises.

Y&c.
DDH

**Comment by venables** [comment]
Thanks @hromi. Unfortunately, I think you may be mistaken. This code [only uses the native Solana Web3.js `generateKeypair()`](https://github.com/m2-labs/vanity-solana/blob/main/lib/vanity-address.ts#L48) method, which only generates on-curve addresses.  This library also gives you the private key along with the vanity address.

Could you have been using a different tool?

**Comment by venables** [comment]
@hromi - I'm closing this issue, as it appears it was created by mistake.  Please feel free to comment here if you have other questions.
